### ISSUE TITLE
About output example_pred.csv

### ISSUE THREAD

**Issue by Chuang1118** [biomed-AI/GraphCS#1]
Hello Author,

Very nice classifier using GNN and PR, good performance with example.RData, even though I don't have GPU. 
I have just a few questions about GraphCS.
I have begin with dataset named "example.RData" in folder of example_data.
```
example <- get(load(file = "/mypath/GraphCS/example_data/example.RData"))
train <- example[[1]]
test <- example[[2]]
length(train@meta.data$CellType) # 1886
length(test@meta.data$CellType) # 7568
head(test@meta.data$CellType) 
[1] "beta"               "delta"              "delta"              "beta"               "activated_stellate" "beta" 
tail(test@meta.data$CellType)
[1] "beta"               "activated_stellate" "alpha"              "beta"               "beta"               "ductal"
```
then, I run on the raw example data for understand better. here just show last step.
```
(graphcs) root@593adf2c6000:~/GraphCS# python -u train.py --data example
--------------------------
Namespace(alpha=0.05, batch=128, bias='none', data='example', dev=3, dropout=0, epochs=1000, gpus=[0], hidden=256, layer=2, lr=0.001, patience=20, rmax=1e-05, rrz=0.5, savepath=3, seed=20159, vat_lr=0.1)
example pre-computation cost: 13.6393 s
over load data
Epoch:0010 train loss:0.154 | val acc:0.966057 | cost3.427
Epoch:0020 train loss:0.129 | val acc:0.971279 | cost6.929
Epoch:0030 train loss:0.116 | val acc:0.968668 | cost10.452
Epoch:0040 train loss:0.114 | val acc:0.968668 | cost13.971
Train cost: 15.0214s
val time cost: 0.3283s
test time: 0.21054911613464355
--------------------------
Test acc:0.971
--------------------------
```
output file :  **example_pred.csv**
```
(graphcs) root@593adf2c6000:~/GraphCS# head example_pred.csv
true_label,pred_label
alpha,alpha
beta,beta
alpha,alpha
ductal,ductal
alpha,alpha
activated_stellate,activated_stellate
ductal,ductal
alpha,alpha
beta,beta
(graphcs) root@593adf2c6000:~/GraphCS# wc -l example_pred.csv
7569 example_pred.csv
(graphcs) root@593adf2c6000:~/GraphCS# tail example_pred.csv
ductal,ductal
ductal,ductal
ductal,ductal
beta,beta
delta,delta
beta,beta
gamma,gamma
ductal,ductal
beta,beta
beta,beta
```
As you mentioned output "The predicted cell labels will be stored in the dataname_pred.csv."
So I think that is only output file.

My principal question is output file doesn't have the barcodes and true label in example_pred.csv doesn't have same order with test@meta.data$CellType in R(see above).
In my case, train as reference labelled spread to test as predict unlabelled using GraphCS, so test acc:0.971 is not my objective, in other word, test@meta.data$CellType are unlabelled. Finally, I need assign pred_label to test@meta.data$CellType by barcode.

Second question concern to your demo example dataset.
In general, Reference dataset has more cells than predict dataset. 
Why in your demo train has 1886 cells and test has 7568 cells ? why not to use switch case statements?
I mean, have you any experiments about the performance and execution time ?

Third question about execution time. 
In your paper figure 6, is CPU time or GPU time?
if it's GPU time, from many cells CPU decreased performance. you know, for the moment the graphics card is out of stock. so I don't have GPU. 10,000 cells in train and 2,000 in test ?  

Last question about graph.
Can I access to the information about edge of graph to see cell relations between labelled and unlabelled cell.
i.e. to get a better understand for how some cells celltype predict that I don't expect and so on. 

Best regards,
Chuang

**Comment by cquzys** [comment]
Hi,
Thank you for your interest in our work.

First, this is a very good problem, because our paper focused on performance comparisons and ignored its ease of use. The reason for this prediction label order upset is due to the fact that we upset the order of cells in the gene expression matrix to enhance the robustness of the model, which is a fundamental technique for training deep learning-based models. We will soon provide an updated version to output the predicted labels with barcodes.

Second, In our experiments, most of the experiments have a larger number of cell types in the reference dataset than in the query dataset, see our paper for details. We provide this example dataset because the size of this dataset happens to be within Github's single maximum file limit. GraphCS is a classifier model, and to make a fair comparison with competing classifier algorithms, we remove cell types that are in the query dataset but not in the reference dataset (we call such cell types as unknown cell types), because generally, classification models do not handle unknown types very well. Of course, you can also use our model to annotate cells directly without any dataset processing, provided that your reference dataset contains as many cell types as possible to cover the query dataset or filter out the unknown cell types by setting a threshold.

Third, Figure 6 shows the GPU time, and we have detailed the training and test sets and the corresponding time in the paper. Even though you don't have a GPU, if you just train on 10,000 cells and test on 2,000 cells, the time overhead is not too long, I mean, this time is acceptable.

Finally, the relationships between cells can be viewed. You can check our graph.py file in the graph_construction file folder, which describes in detail the pairwise relationships of cells.

If you have any more questions, don’t hesitate to let me know.
Best regards,
yuansong zeng

**Comment by cquzys** [comment]
Hi,

I have updated codes for adding barcodes into the output files.
